# image nginx que instalará en el server
FROM nginx
# copy our file default.conf for nginx configuration in correct path-file in server
COPY default.conf /etc/nginx/conf.d/default.conf 
# /etc/nginx/sites-available/pruebas-docker.com
# sudo ln??? /etc/nginx/sites-enable??? /etc/nginx/sites-available   ????